NAME := ftp.module

COMMON_OBJS := 	init/libinit.o init/amiga.o \
				ftp_main.o ftp_lister.o ftp_lister_list.o \
				ftp_lister_xfer.o ftp_lister_connect.o ftp.o \
				ftp_arexx.o ftp_util.o ftp_recursive.o \
				ftp_addressbook.o ftp_addrsupp.o ftp_addrformat.o \
				ftp_protect.o ftp_module.o ftp_data.o ftp_strings.o

OS4_OBJS    :=	init/aos4_ppc_libstub.o \
				init/aos4_68k_to_ppc_vectors.o

OS3_OBJS    :=	init/68k_asm_a4_a5.o

MOS_OBJS    :=	init/mos_ppc_libstub.o
