NAME := about.module

COMMON_OBJS := 	init/libinit.o \
				about.o about_data.o about_jon.o

OS4_OBJS    :=	init/aos4_ppc_libstub.o \
				init/aos4_68k_to_ppc_vectors.o

OS3_OBJS    :=	init/68k_asm_a4_a5.o

MOS_OBJS    :=	init/mos_ppc_libstub.o
