CATCOMP= -flexcat
L= LOCALE:Catalogs/

all: deutsch español français greek italiano magyar nederlands norsk polski português svenska
.PHONY: $(wildcard *)

deutsch:
	$(CATCOMP) /source/Modules/cleanup/cleanup.cd		$@/cleanup.ct CATALOG $@/cleanup.catalog
	$(CATCOMP) /source/Modules/configopus/configopus.cd	$@/configopus.ct CATALOG $@/configopus.catalog
	$(CATCOMP) /source/Modules/diskcopy/diskcopy.cd		$@/diskcopy.ct CATALOG $@/diskcopy.catalog
	$(CATCOMP) /source/Modules/diskinfo/diskinfo.cd		$@/diskinfo.ct CATALOG $@/diskinfo.catalog
	$(CATCOMP) /source/Program/dopus.cd			$@/dopus.ct CATALOG $@/dopus.catalog
	$(CATCOMP) /source/Library/dopuslib.cd			$@/dopuslib.ct CATALOG $@/dopuslib.catalog
	$(CATCOMP) /source/Modules/filetype/filetype.cd		$@/filetype.ct CATALOG $@/filetype.catalog
	$(CATCOMP) /source/Misc/C/ViewFont/font.cd		$@/font.ct CATALOG $L$@/viewfont.catalog
	$(CATCOMP) /source/Modules/format/format.cd		$@/format.ct CATALOG $@/format.catalog
	$(CATCOMP) /source/Modules/ftp/ftp.cd			$@/ftp.ct CATALOG $@/ftp.catalog
	$(CATCOMP) /source/Modules/icon/icon.cd			$@/icon.ct CATALOG $@/icon.catalog
	$(CATCOMP) /source/Modules/join/join.cd			$@/join.ct CATALOG $@/join.catalog
	$(CATCOMP) /source/Modules/listerformat/listerformat.cd	$@/listerformat.ct CATALOG $@/listerformat.catalog
	$(CATCOMP) /source/Modules/misc/misc.cd			$@/misc.ct CATALOG $@/misc.catalog
	$(CATCOMP) /source/Modules/pathformat/pathformat.cd	$@/pathformat.ct CATALOG $@/pathformat.catalog
	$(CATCOMP) /source/Modules/play/play.cd			$@/play.ct CATALOG $@/play.catalog
	$(CATCOMP) /source/Modules/print/print.cd		$@/print.ct CATALOG $@/print.catalog
	$(CATCOMP) /source/Modules/read/read.cd			$@/read.ct CATALOG $@/read.catalog
	$(CATCOMP) /source/Modules/show/show.cd			$@/show.ct CATALOG $@/show.catalog

español:
	$(CATCOMP) /source/Modules/cleanup/cleanup.cd		$@/cleanup.ct CATALOG $@/cleanup.catalog
	$(CATCOMP) /source/Modules/configopus/configopus.cd	$@/configopus.ct CATALOG $@/configopus.catalog
	$(CATCOMP) /source/Modules/diskcopy/diskcopy.cd		$@/diskcopy.ct CATALOG $@/diskcopy.catalog
	$(CATCOMP) /source/Modules/diskinfo/diskinfo.cd		$@/diskinfo.ct CATALOG $@/diskinfo.catalog
	$(CATCOMP) /source/Program/dopus.cd			$@/dopus.ct CATALOG $@/dopus.catalog
	$(CATCOMP) /source/Library/dopuslib.cd			$@/dopuslib.ct CATALOG $@/dopuslib.catalog
	$(CATCOMP) /source/Modules/filetype/filetype.cd		$@/filetype.ct CATALOG $@/filetype.catalog
	#$(CATCOMP) /source/Misc/C/ViewFont/font.cd		$@/font.ct CATALOG $L$@/viewfont.catalog
	$(CATCOMP) /source/Modules/format/format.cd		$@/format.ct CATALOG $@/format.catalog
	$(CATCOMP) /source/Modules/ftp/ftp.cd			$@/ftp.ct CATALOG $@/ftp.catalog
	$(CATCOMP) /source/Modules/icon/icon.cd			$@/icon.ct CATALOG $@/icon.catalog
	$(CATCOMP) /source/Modules/join/join.cd			$@/join.ct CATALOG $@/join.catalog
	$(CATCOMP) /source/Modules/listerformat/listerformat.cd	$@/listerformat.ct CATALOG $@/listerformat.catalog
	$(CATCOMP) /source/Modules/misc/misc.cd			$@/misc.ct CATALOG $@/misc.catalog
	$(CATCOMP) /source/Modules/pathformat/pathformat.cd	$@/pathformat.ct CATALOG $@/pathformat.catalog
	$(CATCOMP) /source/Modules/play/play.cd			$@/play.ct CATALOG $@/play.catalog
	$(CATCOMP) /source/Modules/print/print.cd		$@/print.ct CATALOG $@/print.catalog
	$(CATCOMP) /source/Modules/read/read.cd			$@/read.ct CATALOG $@/read.catalog
	$(CATCOMP) /source/Modules/show/show.cd			$@/show.ct CATALOG $@/show.catalog

français:
	$(CATCOMP) /source/Modules/cleanup/cleanup.cd		$@/cleanup.ct CATALOG $@/cleanup.catalog
	$(CATCOMP) /source/Modules/configopus/configopus.cd	$@/configopus.ct CATALOG $@/configopus.catalog
	$(CATCOMP) /source/Modules/diskcopy/diskcopy.cd		$@/diskcopy.ct CATALOG $@/diskcopy.catalog
	$(CATCOMP) /source/Modules/diskinfo/diskinfo.cd		$@/diskinfo.ct CATALOG $@/diskinfo.catalog
	$(CATCOMP) /source/Program/dopus.cd			$@/dopus.ct CATALOG $@/dopus.catalog
	$(CATCOMP) /source/Library/dopuslib.cd			$@/dopuslib.ct CATALOG $@/dopuslib.catalog
	$(CATCOMP) /source/Modules/filetype/filetype.cd		$@/filetype.ct CATALOG $@/filetype.catalog
	#$(CATCOMP) /source/Misc/C/ViewFont/font.cd		$@/font.ct CATALOG $L$@/viewfont.catalog
	$(CATCOMP) /source/Modules/format/format.cd		$@/format.ct CATALOG $@/format.catalog
	$(CATCOMP) /source/Modules/ftp/ftp.cd			$@/ftp.ct CATALOG $@/ftp.catalog
	$(CATCOMP) /source/Modules/icon/icon.cd			$@/icon.ct CATALOG $@/icon.catalog
	$(CATCOMP) /source/Modules/join/join.cd			$@/join.ct CATALOG $@/join.catalog
	$(CATCOMP) /source/Modules/listerformat/listerformat.cd	$@/listerformat.ct CATALOG $@/listerformat.catalog
	$(CATCOMP) /source/Modules/misc/misc.cd			$@/misc.ct CATALOG $@/misc.catalog
	$(CATCOMP) /source/Modules/pathformat/pathformat.cd	$@/pathformat.ct CATALOG $@/pathformat.catalog
	$(CATCOMP) /source/Modules/play/play.cd			$@/play.ct CATALOG $@/play.catalog
	$(CATCOMP) /source/Modules/print/print.cd		$@/print.ct CATALOG $@/print.catalog
	$(CATCOMP) /source/Modules/read/read.cd			$@/read.ct CATALOG $@/read.catalog
	$(CATCOMP) /source/Modules/show/show.cd			$@/show.ct CATALOG $@/show.catalog

greek:
	$(CATCOMP) /source/Modules/cleanup/cleanup.cd		$@/cleanup.ct CATALOG $@/cleanup.catalog
	$(CATCOMP) /source/Modules/configopus/configopus.cd	$@/configopus.ct CATALOG $@/configopus.catalog
	$(CATCOMP) /source/Modules/diskcopy/diskcopy.cd		$@/diskcopy.ct CATALOG $@/diskcopy.catalog
	$(CATCOMP) /source/Modules/diskinfo/diskinfo.cd		$@/diskinfo.ct CATALOG $@/diskinfo.catalog
	$(CATCOMP) /source/Program/dopus.cd			$@/dopus.ct CATALOG $@/dopus.catalog
	$(CATCOMP) /source/Library/dopuslib.cd			$@/dopuslib.ct CATALOG $@/dopuslib.catalog
	$(CATCOMP) /source/Modules/filetype/filetype.cd		$@/filetype.ct CATALOG $@/filetype.catalog
	#$(CATCOMP) /source/Misc/C/ViewFont/font.cd		$@/font.ct CATALOG $L$@/viewfont.catalog
	$(CATCOMP) /source/Modules/format/format.cd		$@/format.ct CATALOG $@/format.catalog
	$(CATCOMP) /source/Modules/ftp/ftp.cd			$@/ftp.ct CATALOG $@/ftp.catalog
	$(CATCOMP) /source/Modules/icon/icon.cd			$@/icon.ct CATALOG $@/icon.catalog
	$(CATCOMP) /source/Modules/join/join.cd			$@/join.ct CATALOG $@/join.catalog
	$(CATCOMP) /source/Modules/listerformat/listerformat.cd	$@/listerformat.ct CATALOG $@/listerformat.catalog
	$(CATCOMP) /source/Modules/misc/misc.cd			$@/misc.ct CATALOG $@/misc.catalog
	$(CATCOMP) /source/Modules/pathformat/pathformat.cd	$@/pathformat.ct CATALOG $@/pathformat.catalog
	$(CATCOMP) /source/Modules/play/play.cd			$@/play.ct CATALOG $@/play.catalog
	$(CATCOMP) /source/Modules/print/print.cd		$@/print.ct CATALOG $@/print.catalog
	$(CATCOMP) /source/Modules/read/read.cd			$@/read.ct CATALOG $@/read.catalog
	$(CATCOMP) /source/Modules/show/show.cd			$@/show.ct CATALOG $@/show.catalog

italiano:
	$(CATCOMP) /source/Modules/cleanup/cleanup.cd		$@/cleanup.ct CATALOG $@/cleanup.catalog
	$(CATCOMP) /source/Modules/configopus/configopus.cd	$@/configopus.ct CATALOG $@/configopus.catalog
	$(CATCOMP) /source/Modules/diskcopy/diskcopy.cd		$@/diskcopy.ct CATALOG $@/diskcopy.catalog
	$(CATCOMP) /source/Modules/diskinfo/diskinfo.cd		$@/diskinfo.ct CATALOG $@/diskinfo.catalog
	$(CATCOMP) /source/Program/dopus.cd			$@/dopus.ct CATALOG $@/dopus.catalog
	$(CATCOMP) /source/Library/dopuslib.cd			$@/dopuslib.ct CATALOG $@/dopuslib.catalog
	$(CATCOMP) /source/Modules/filetype/filetype.cd		$@/filetype.ct CATALOG $@/filetype.catalog
	#$(CATCOMP) /source/Misc/C/ViewFont/font.cd		$@/font.ct CATALOG $L$@/viewfont.catalog
	$(CATCOMP) /source/Modules/format/format.cd		$@/format.ct CATALOG $@/format.catalog
	$(CATCOMP) /source/Modules/ftp/ftp.cd			$@/ftp.ct CATALOG $@/ftp.catalog
	$(CATCOMP) /source/Modules/icon/icon.cd			$@/icon.ct CATALOG $@/icon.catalog
	$(CATCOMP) /source/Modules/join/join.cd			$@/join.ct CATALOG $@/join.catalog
	$(CATCOMP) /source/Modules/listerformat/listerformat.cd	$@/listerformat.ct CATALOG $@/listerformat.catalog
	$(CATCOMP) /source/Modules/misc/misc.cd			$@/misc.ct CATALOG $@/misc.catalog
	$(CATCOMP) /source/Modules/pathformat/pathformat.cd	$@/pathformat.ct CATALOG $@/pathformat.catalog
	$(CATCOMP) /source/Modules/play/play.cd			$@/play.ct CATALOG $@/play.catalog
	$(CATCOMP) /source/Modules/print/print.cd		$@/print.ct CATALOG $@/print.catalog
	$(CATCOMP) /source/Modules/read/read.cd			$@/read.ct CATALOG $@/read.catalog
	$(CATCOMP) /source/Modules/show/show.cd			$@/show.ct CATALOG $@/show.catalog

magyar:
	$(CATCOMP) /source/Modules/cleanup/cleanup.cd		$@/cleanup.ct CATALOG $@/cleanup.catalog
	$(CATCOMP) /source/Modules/configopus/configopus.cd	$@/configopus.ct CATALOG $@/configopus.catalog
	$(CATCOMP) /source/Modules/diskcopy/diskcopy.cd		$@/diskcopy.ct CATALOG $@/diskcopy.catalog
	$(CATCOMP) /source/Modules/diskinfo/diskinfo.cd		$@/diskinfo.ct CATALOG $@/diskinfo.catalog
	$(CATCOMP) /source/Program/dopus.cd			$@/dopus.ct CATALOG $@/dopus.catalog
	$(CATCOMP) /source/Library/dopuslib.cd			$@/dopuslib.ct CATALOG $@/dopuslib.catalog
	$(CATCOMP) /source/Modules/filetype/filetype.cd		$@/filetype.ct CATALOG $@/filetype.catalog
	#$(CATCOMP) /source/Misc/C/ViewFont/font.cd		$@/font.ct CATALOG $L$@/viewfont.catalog
	$(CATCOMP) /source/Modules/format/format.cd		$@/format.ct CATALOG $@/format.catalog
	$(CATCOMP) /source/Modules/ftp/ftp.cd			$@/ftp.ct CATALOG $@/ftp.catalog
	$(CATCOMP) /source/Modules/icon/icon.cd			$@/icon.ct CATALOG $@/icon.catalog
	$(CATCOMP) /source/Modules/join/join.cd			$@/join.ct CATALOG $@/join.catalog
	$(CATCOMP) /source/Modules/listerformat/listerformat.cd	$@/listerformat.ct CATALOG $@/listerformat.catalog
	$(CATCOMP) /source/Modules/misc/misc.cd			$@/misc.ct CATALOG $@/misc.catalog
	$(CATCOMP) /source/Modules/pathformat/pathformat.cd	$@/pathformat.ct CATALOG $@/pathformat.catalog
	$(CATCOMP) /source/Modules/play/play.cd			$@/play.ct CATALOG $@/play.catalog
	$(CATCOMP) /source/Modules/print/print.cd		$@/print.ct CATALOG $@/print.catalog
	$(CATCOMP) /source/Modules/read/read.cd			$@/read.ct CATALOG $@/read.catalog
	$(CATCOMP) /source/Modules/show/show.cd			$@/show.ct CATALOG $@/show.catalog

nederlands:
	$(CATCOMP) /source/Modules/cleanup/cleanup.cd		$@/cleanup.ct CATALOG $@/cleanup.catalog
	$(CATCOMP) /source/Modules/configopus/configopus.cd	$@/configopus.ct CATALOG $@/configopus.catalog
	$(CATCOMP) /source/Modules/diskcopy/diskcopy.cd		$@/diskcopy.ct CATALOG $@/diskcopy.catalog
	$(CATCOMP) /source/Modules/diskinfo/diskinfo.cd		$@/diskinfo.ct CATALOG $@/diskinfo.catalog
	$(CATCOMP) /source/Program/dopus.cd			$@/dopus.ct CATALOG $@/dopus.catalog
	$(CATCOMP) /source/Library/dopuslib.cd			$@/dopuslib.ct CATALOG $@/dopuslib.catalog
	$(CATCOMP) /source/Modules/filetype/filetype.cd		$@/filetype.ct CATALOG $@/filetype.catalog
	#$(CATCOMP) /source/Misc/C/ViewFont/font.cd		$@/font.ct CATALOG $L$@/viewfont.catalog
	$(CATCOMP) /source/Modules/format/format.cd		$@/format.ct CATALOG $@/format.catalog
	$(CATCOMP) /source/Modules/ftp/ftp.cd			$@/ftp.ct CATALOG $@/ftp.catalog
	$(CATCOMP) /source/Modules/icon/icon.cd			$@/icon.ct CATALOG $@/icon.catalog
	$(CATCOMP) /source/Modules/join/join.cd			$@/join.ct CATALOG $@/join.catalog
	$(CATCOMP) /source/Modules/listerformat/listerformat.cd	$@/listerformat.ct CATALOG $@/listerformat.catalog
	$(CATCOMP) /source/Modules/misc/misc.cd			$@/misc.ct CATALOG $@/misc.catalog
	$(CATCOMP) /source/Modules/pathformat/pathformat.cd	$@/pathformat.ct CATALOG $@/pathformat.catalog
	$(CATCOMP) /source/Modules/play/play.cd			$@/play.ct CATALOG $@/play.catalog
	$(CATCOMP) /source/Modules/print/print.cd		$@/print.ct CATALOG $@/print.catalog
	$(CATCOMP) /source/Modules/read/read.cd			$@/read.ct CATALOG $@/read.catalog
	$(CATCOMP) /source/Modules/show/show.cd			$@/show.ct CATALOG $@/show.catalog

norsk:
	$(CATCOMP) /source/Modules/cleanup/cleanup.cd		$@/cleanup.ct CATALOG $@/cleanup.catalog
	$(CATCOMP) /source/Modules/configopus/configopus.cd	$@/configopus.ct CATALOG $@/configopus.catalog
	$(CATCOMP) /source/Modules/diskcopy/diskcopy.cd		$@/diskcopy.ct CATALOG $@/diskcopy.catalog
	$(CATCOMP) /source/Modules/diskinfo/diskinfo.cd		$@/diskinfo.ct CATALOG $@/diskinfo.catalog
	$(CATCOMP) /source/Program/dopus.cd			$@/dopus.ct CATALOG $@/dopus.catalog
	$(CATCOMP) /source/Library/dopuslib.cd			$@/dopuslib.ct CATALOG $@/dopuslib.catalog
	$(CATCOMP) /source/Modules/filetype/filetype.cd		$@/filetype.ct CATALOG $@/filetype.catalog
	#$(CATCOMP) /source/Misc/C/ViewFont/font.cd		$@/font.ct CATALOG $L$@/viewfont.catalog
	$(CATCOMP) /source/Modules/format/format.cd		$@/format.ct CATALOG $@/format.catalog
	$(CATCOMP) /source/Modules/ftp/ftp.cd			$@/ftp.ct CATALOG $@/ftp.catalog
	$(CATCOMP) /source/Modules/icon/icon.cd			$@/icon.ct CATALOG $@/icon.catalog
	$(CATCOMP) /source/Modules/join/join.cd			$@/join.ct CATALOG $@/join.catalog
	$(CATCOMP) /source/Modules/listerformat/listerformat.cd	$@/listerformat.ct CATALOG $@/listerformat.catalog
	$(CATCOMP) /source/Modules/misc/misc.cd			$@/misc.ct CATALOG $@/misc.catalog
	$(CATCOMP) /source/Modules/pathformat/pathformat.cd	$@/pathformat.ct CATALOG $@/pathformat.catalog
	$(CATCOMP) /source/Modules/play/play.cd			$@/play.ct CATALOG $@/play.catalog
	$(CATCOMP) /source/Modules/print/print.cd		$@/print.ct CATALOG $@/print.catalog
	$(CATCOMP) /source/Modules/read/read.cd			$@/read.ct CATALOG $@/read.catalog
	$(CATCOMP) /source/Modules/show/show.cd			$@/show.ct CATALOG $@/show.catalog

polski:
	$(CATCOMP) /source/Modules/cleanup/cleanup.cd		$@/cleanup.ct CATALOG $@/cleanup.catalog
	$(CATCOMP) /source/Modules/configopus/configopus.cd	$@/configopus.ct CATALOG $@/configopus.catalog
	$(CATCOMP) /source/Modules/diskcopy/diskcopy.cd		$@/diskcopy.ct CATALOG $@/diskcopy.catalog
	$(CATCOMP) /source/Modules/diskinfo/diskinfo.cd		$@/diskinfo.ct CATALOG $@/diskinfo.catalog
	$(CATCOMP) /source/Program/dopus.cd			$@/dopus.ct CATALOG $@/dopus.catalog
	$(CATCOMP) /source/Library/dopuslib.cd			$@/dopuslib.ct CATALOG $@/dopuslib.catalog
	$(CATCOMP) /source/Modules/filetype/filetype.cd		$@/filetype.ct CATALOG $@/filetype.catalog
	#$(CATCOMP) /source/Misc/C/ViewFont/font.cd		$@/font.ct CATALOG $L$@/viewfont.catalog
	$(CATCOMP) /source/Modules/format/format.cd		$@/format.ct CATALOG $@/format.catalog
	$(CATCOMP) /source/Modules/ftp/ftp.cd			$@/ftp.ct CATALOG $@/ftp.catalog
	$(CATCOMP) /source/Modules/icon/icon.cd			$@/icon.ct CATALOG $@/icon.catalog
	$(CATCOMP) /source/Modules/join/join.cd			$@/join.ct CATALOG $@/join.catalog
	$(CATCOMP) /source/Modules/listerformat/listerformat.cd	$@/listerformat.ct CATALOG $@/listerformat.catalog
	$(CATCOMP) /source/Modules/misc/misc.cd			$@/misc.ct CATALOG $@/misc.catalog
	$(CATCOMP) /source/Modules/pathformat/pathformat.cd	$@/pathformat.ct CATALOG $@/pathformat.catalog
	$(CATCOMP) /source/Modules/play/play.cd			$@/play.ct CATALOG $@/play.catalog
	$(CATCOMP) /source/Modules/print/print.cd		$@/print.ct CATALOG $@/print.catalog
	$(CATCOMP) /source/Modules/read/read.cd			$@/read.ct CATALOG $@/read.catalog
	$(CATCOMP) /source/Modules/show/show.cd			$@/show.ct CATALOG $@/show.catalog

português:
	$(CATCOMP) /source/Modules/cleanup/cleanup.cd		$@/cleanup.ct CATALOG $@/cleanup.catalog
	$(CATCOMP) /source/Modules/configopus/configopus.cd	$@/configopus.ct CATALOG $@/configopus.catalog
	$(CATCOMP) /source/Modules/diskcopy/diskcopy.cd		$@/diskcopy.ct CATALOG $@/diskcopy.catalog
	$(CATCOMP) /source/Modules/diskinfo/diskinfo.cd		$@/diskinfo.ct CATALOG $@/diskinfo.catalog
	$(CATCOMP) /source/Program/dopus.cd			$@/dopus.ct CATALOG $@/dopus.catalog
	$(CATCOMP) /source/Library/dopuslib.cd			$@/dopuslib.ct CATALOG $@/dopuslib.catalog
	$(CATCOMP) /source/Modules/filetype/filetype.cd		$@/filetype.ct CATALOG $@/filetype.catalog
	#$(CATCOMP) /source/Misc/C/ViewFont/font.cd		$@/font.ct CATALOG $L$@/viewfont.catalog
	$(CATCOMP) /source/Modules/format/format.cd		$@/format.ct CATALOG $@/format.catalog
	$(CATCOMP) /source/Modules/ftp/ftp.cd			$@/ftp.ct CATALOG $@/ftp.catalog
	$(CATCOMP) /source/Modules/icon/icon.cd			$@/icon.ct CATALOG $@/icon.catalog
	$(CATCOMP) /source/Modules/join/join.cd			$@/join.ct CATALOG $@/join.catalog
	$(CATCOMP) /source/Modules/listerformat/listerformat.cd	$@/listerformat.ct CATALOG $@/listerformat.catalog
	$(CATCOMP) /source/Modules/misc/misc.cd			$@/misc.ct CATALOG $@/misc.catalog
	$(CATCOMP) /source/Modules/pathformat/pathformat.cd	$@/pathformat.ct CATALOG $@/pathformat.catalog
	$(CATCOMP) /source/Modules/play/play.cd			$@/play.ct CATALOG $@/play.catalog
	$(CATCOMP) /source/Modules/print/print.cd		$@/print.ct CATALOG $@/print.catalog
	$(CATCOMP) /source/Modules/read/read.cd			$@/read.ct CATALOG $@/read.catalog
	$(CATCOMP) /source/Modules/show/show.cd			$@/show.ct CATALOG $@/show.catalog

svenska:
	$(CATCOMP) /source/Modules/cleanup/cleanup.cd		$@/cleanup.ct CATALOG $@/cleanup.catalog
	$(CATCOMP) /source/Modules/configopus/configopus.cd	$@/configopus.ct CATALOG $@/configopus.catalog
	$(CATCOMP) /source/Modules/diskcopy/diskcopy.cd		$@/diskcopy.ct CATALOG $@/diskcopy.catalog
	$(CATCOMP) /source/Modules/diskinfo/diskinfo.cd		$@/diskinfo.ct CATALOG $@/diskinfo.catalog
	$(CATCOMP) /source/Program/dopus.cd			$@/dopus.ct CATALOG $@/dopus.catalog
	$(CATCOMP) /source/Library/dopuslib.cd			$@/dopuslib.ct CATALOG $@/dopuslib.catalog
	$(CATCOMP) /source/Modules/filetype/filetype.cd		$@/filetype.ct CATALOG $@/filetype.catalog
	#$(CATCOMP) /source/Misc/C/ViewFont/font.cd		$@/font.ct CATALOG $L$@/viewfont.catalog
	$(CATCOMP) /source/Modules/format/format.cd		$@/format.ct CATALOG $@/format.catalog
	$(CATCOMP) /source/Modules/ftp/ftp.cd			$@/ftp.ct CATALOG $@/ftp.catalog
	$(CATCOMP) /source/Modules/icon/icon.cd			$@/icon.ct CATALOG $@/icon.catalog
	$(CATCOMP) /source/Modules/join/join.cd			$@/join.ct CATALOG $@/join.catalog
	$(CATCOMP) /source/Modules/listerformat/listerformat.cd	$@/listerformat.ct CATALOG $@/listerformat.catalog
	$(CATCOMP) /source/Modules/misc/misc.cd			$@/misc.ct CATALOG $@/misc.catalog
	$(CATCOMP) /source/Modules/pathformat/pathformat.cd	$@/pathformat.ct CATALOG $@/pathformat.catalog
	$(CATCOMP) /source/Modules/play/play.cd			$@/play.ct CATALOG $@/play.catalog
	$(CATCOMP) /source/Modules/print/print.cd		$@/print.ct CATALOG $@/print.catalog
	$(CATCOMP) /source/Modules/read/read.cd			$@/read.ct CATALOG $@/read.catalog
	$(CATCOMP) /source/Modules/show/show.cd			$@/show.ct CATALOG $@/show.catalog
