#ifndef MODULE_INTERFACE_DEF_H
#define MODULE_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.5.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif


#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct ModuleIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct ModuleIFace *Self);
	uint32 APICALL (*Release)(struct ModuleIFace *Self);
	void APICALL (*Expunge)(struct ModuleIFace *Self);
	struct Interface * APICALL (*Clone)(struct ModuleIFace *Self);
	int APICALL (*Module_Entry)(struct ModuleIFace *Self, struct List * files, struct Screen * screen, IPCData * ipc, IPCData * main_ipc, ULONG id, ULONG data);
	ModuleInfo * APICALL (*Module_Identify)(struct ModuleIFace *Self, int num);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* MODULE_INTERFACE_DEF_H */
