#ifndef SYSINFO_INTERFACE_DEF_H
#define SYSINFO_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.5.
** Do not edit
*/

#ifndef EXEC_TYPES_H
	#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
	#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
	#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_SYSINFO_H
	#include <libraries/SysInfo.h>
#endif

#ifdef __cplusplus
	#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
	#endif
extern "C" {
#endif

struct SysInfoIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct SysInfoIFace *Self);
	uint32 APICALL (*Release)(struct SysInfoIFace *Self);
	void APICALL (*Expunge)(struct SysInfoIFace *Self);
	struct Interface *APICALL (*Clone)(struct SysInfoIFace *Self);
	struct SysInfo *APICALL (*InitSysInfo)(struct SysInfoIFace *Self);
	void APICALL (*FreeSysInfo)(struct SysInfoIFace *Self, struct SysInfo *si);
	void APICALL (*GetLoadAverage)(struct SysInfoIFace *Self, struct SysInfo *si, struct SI_LoadAverage *la);
	LONG APICALL (*GetPid)(struct SysInfoIFace *Self, struct SysInfo *si);
	LONG APICALL (*GetPpid)(struct SysInfoIFace *Self, struct SysInfo *si);
	LONG APICALL (*GetPgrp)(struct SysInfoIFace *Self, struct SysInfo *si);
	LONG APICALL (*GetNice)(struct SysInfoIFace *Self, struct SysInfo *si, LONG which, LONG who);
	LONG APICALL (*SetNice)(struct SysInfoIFace *Self, struct SysInfo *si, LONG which, LONG who, LONG nice);
	struct SI_Notify *APICALL (*AddNotify)(struct SysInfoIFace *Self,
										   struct SysInfo *si,
										   WORD flags,
										   LONG safety_limit);
	void APICALL (*RemoveNotify)(struct SysInfoIFace *Self, struct SysInfo *si, struct SI_Notify *notify);
	void APICALL (*GetCpuUsage)(struct SysInfoIFace *Self, struct SysInfo *si, struct SI_CpuUsage *usage);
	LONG APICALL (*GetTaskCpuUsage)(struct SysInfoIFace *Self,
									struct SysInfo *si,
									struct SI_TaskCpuUsage *usage,
									struct Task *task);
};

#ifdef __cplusplus
}
	#ifdef __USE_AMIGAOS_NAMESPACE__
}
	#endif
#endif

#endif /* SYSINFO_INTERFACE_DEF_H */
