#ifndef XADMODULE_INTERFACE_DEF_H
#define XADMODULE_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.5.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif


#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct XADModuleIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct XADModuleIFace *Self);
	uint32 APICALL (*Release)(struct XADModuleIFace *Self);
	void APICALL (*Expunge)(struct XADModuleIFace *Self);
	struct Interface * APICALL (*Clone)(struct XADModuleIFace *Self);
	int APICALL (*Module_Entry)(struct XADModuleIFace *Self, struct List * files, struct Screen * screen, IPCData * ipc, IPCData * main_ipc, ULONG id, ULONG data);
	ModuleInfo * APICALL (*Module_Identify)(struct XADModuleIFace *Self, int num);
	ULONG APICALL (*ProgressHook)(struct XADModuleIFace *Self, struct Hook * hook, struct xadProgressInfo * xpi);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* XADMODULE_INTERFACE_DEF_H */
