#ifndef MUSIC_INTERFACE_DEF_H
#define MUSIC_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.5.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif


#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct MUSICIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct MUSICIFace *Self);
	uint32 APICALL (*Release)(struct MUSICIFace *Self);
	void APICALL (*Expunge)(struct MUSICIFace *Self);
	struct Interface * APICALL (*Clone)(struct MUSICIFace *Self);
	WORD APICALL (*PlayModule)(struct MUSICIFace *Self, char * par1, BOOL last);
	VOID APICALL (*StopModule)(struct MUSICIFace *Self);
	WORD APICALL (*IsModule)(struct MUSICIFace *Self, char * last);
	VOID APICALL (*FlushModule)(struct MUSICIFace *Self);
	VOID APICALL (*ContModule)(struct MUSICIFace *Self);
	VOID APICALL (*SetVolume)(struct MUSICIFace *Self, WORD last);
	VOID APICALL (*PlayFaster)(struct MUSICIFace *Self);
	VOID APICALL (*PlaySlower)(struct MUSICIFace *Self);
	VOID APICALL (*TempoReset)(struct MUSICIFace *Self);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* MUSIC_INTERFACE_DEF_H */
