/*
** This file was automatically generated by fdtrans 52.1.
** Do not edit it by hand. Instead, edit the sfd file
** that was used to generate this file
*/

#ifdef __USE_INLINE__
#undef __USE_INLINE__
#endif
#ifndef __NOGLOBALIFACE__
#define __NOGLOBALIFACE__
#endif

#include <proto/dopus5.h>
#include <exec/interfaces.h>
#include <exec/libraries.h>
#include <exec/emulation.h>
#include <interfaces/exec.h>
#include <interfaces/configopus.h>
#include <proto/configopus.h>


static inline int8  convert_int8 (uint32 x) { return x; }
static inline int16 convert_int16(uint32 x) { return x; }


STATIC struct Library * stub_OpenPPC(ULONG *regarray)
{
    struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
    struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
    struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

    return Self->Open(0);
}
STATIC CONST struct EmuTrap stub_Open = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_OpenPPC };

STATIC APTR stub_ClosePPC(ULONG *regarray)
{
    struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
    struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
    struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

    return Self->Close();
}
STATIC CONST struct EmuTrap stub_Close = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_ClosePPC };

STATIC APTR stub_ExpungePPC(ULONG *regarray __attribute__((unused)))
{
    return NULL;
}
STATIC CONST struct EmuTrap stub_Expunge = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_ExpungePPC };

STATIC ULONG stub_ReservedPPC(ULONG *regarray __attribute__((unused)))
{
    return 0UL;
}
STATIC CONST struct EmuTrap stub_Reserved = { TRAPINST, TRAPTYPE, stub_ReservedPPC };

static int stub_Config_SettingsPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ConfigOpusIFace *Self = (struct ConfigOpusIFace *) ExtLib->MainIFace;

	return Self->Config_Settings(
		(Cfg_Environment *)regarray[8],
		(struct Screen *)regarray[9],
		(IPCData *)regarray[10],
		(IPCData *)regarray[11],
		(char *)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_Config_Settings = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_Config_SettingsPPC };

static unsigned long stub_Config_EnvironmentPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ConfigOpusIFace *Self = (struct ConfigOpusIFace *) ExtLib->MainIFace;

	return Self->Config_Environment(
		(Cfg_Environment *)regarray[8],
		(struct Screen *)regarray[9],
		(UWORD *)regarray[10],
		(IPCData *)regarray[11],
		(IPCData *)regarray[12],
		(UWORD)(regarray[0] & 0xffff),
		(ULONG *)regarray[13],
		(char *)regarray[1],
		(Att_List *)regarray[2]
	);
}
STATIC CONST struct EmuTrap stub_Config_Environment = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_Config_EnvironmentPPC };

static int stub_Config_ButtonsPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ConfigOpusIFace *Self = (struct ConfigOpusIFace *) ExtLib->MainIFace;

	return Self->Config_Buttons(
		(ButtonsStartup *)regarray[8],
		(IPCData *)regarray[9],
		(IPCData *)regarray[10],
		(struct Screen *)regarray[11],
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_Config_Buttons = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_Config_ButtonsPPC };

static BOOL stub_ConvertConfigPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ConfigOpusIFace *Self = (struct ConfigOpusIFace *) ExtLib->MainIFace;

	return Self->ConvertConfig(
		(char *)regarray[8],
		(struct Screen *)regarray[9],
		(IPCData *)regarray[10]
	);
}
STATIC CONST struct EmuTrap stub_ConvertConfig = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_ConvertConfigPPC };

static short stub_Config_FiletypesPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ConfigOpusIFace *Self = (struct ConfigOpusIFace *) ExtLib->MainIFace;

	return Self->Config_Filetypes(
		(struct Screen *)regarray[8],
		(IPCData *)regarray[9],
		(IPCData *)regarray[10],
		(ULONG)regarray[0],
		(char *)regarray[11]
	);
}
STATIC CONST struct EmuTrap stub_Config_Filetypes = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_Config_FiletypesPPC };

static ULONG stub_Config_ListerButtonsPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ConfigOpusIFace *Self = (struct ConfigOpusIFace *) ExtLib->MainIFace;

	return Self->Config_ListerButtons(
		(char *)regarray[8],
		(IPCData *)regarray[9],
		(IPCData *)regarray[10],
		(struct Screen *)regarray[11],
		(Cfg_ButtonBank *)regarray[12],
		(ULONG)regarray[0],
		(LONG)regarray[1]
	);
}
STATIC CONST struct EmuTrap stub_Config_ListerButtons = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_Config_ListerButtonsPPC };

static ULONG stub_Config_MenuPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ConfigOpusIFace *Self = (struct ConfigOpusIFace *) ExtLib->MainIFace;

	return Self->Config_Menu(
		(char *)regarray[8],
		(IPCData *)regarray[9],
		(IPCData *)regarray[10],
		(struct Screen *)regarray[11],
		(Cfg_ButtonBank *)regarray[12],
		(char *)regarray[13],
		(ULONG)regarray[0],
		(char *)regarray[1],
		(short)convert_int16(regarray[2]),
		(Att_List *)regarray[3]
	);
}
STATIC CONST struct EmuTrap stub_Config_Menu = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_Config_MenuPPC };

static ULONG stub_Config_MenusPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ConfigOpusIFace *Self = (struct ConfigOpusIFace *) ExtLib->MainIFace;

	return Self->Config_Menus(
		(IPCData *)regarray[8],
		(IPCData *)regarray[9],
		(struct Screen *)regarray[10],
		(Cfg_ButtonBank *)regarray[11],
		(ULONG)regarray[0],
		(ULONG)regarray[1],
		(char *)regarray[2]
	);
}
STATIC CONST struct EmuTrap stub_Config_Menus = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_Config_MenusPPC };

static Cfg_Filetype * stub_EditFiletypePPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ConfigOpusIFace *Self = (struct ConfigOpusIFace *) ExtLib->MainIFace;

	return Self->EditFiletype(
		(Cfg_Filetype *)regarray[8],
		(struct Window *)regarray[9],
		(IPCData *)regarray[10],
		(IPCData *)regarray[11],
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_EditFiletype = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_EditFiletypePPC };

static Cfg_Function * stub_Config_EditFunctionPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ConfigOpusIFace *Self = (struct ConfigOpusIFace *) ExtLib->MainIFace;

	return Self->Config_EditFunction(
		(IPCData *)regarray[8],
		(IPCData *)regarray[9],
		(struct Window *)regarray[10],
		(Cfg_Function *)regarray[11],
		(APTR)regarray[12],
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_Config_EditFunction = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_Config_EditFunctionPPC };

static long stub_ShowPaletteBoxPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ConfigOpusIFace *Self = (struct ConfigOpusIFace *) ExtLib->MainIFace;

	return Self->ShowPaletteBox(
		(struct Window *)regarray[8],
		(DOpusScreenData *)regarray[9],
		(short *)regarray[10],
		(short *)regarray[11],
		(struct TextAttr *)regarray[12],
		(ColourSpec32 *)regarray[13],
		(short *)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_ShowPaletteBox = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_ShowPaletteBoxPPC };

static BOOL stub_FunctionExportASCIIPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ConfigOpusIFace *Self = (struct ConfigOpusIFace *) ExtLib->MainIFace;

	return Self->FunctionExportASCII(
		(char *)regarray[8],
		(Cfg_Button *)regarray[9],
		(Cfg_Function *)regarray[10],
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_FunctionExportASCII = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_FunctionExportASCIIPPC };

CONST CONST_APTR VecTable68K[] =
{
	&stub_Open,
	&stub_Close,
	&stub_Expunge,
	&stub_Reserved,
	&stub_Config_Settings,
	&stub_Config_Environment,
	&stub_Reserved,
	&stub_Config_Buttons,
	&stub_ConvertConfig,
	&stub_Config_Filetypes,
	&stub_Config_ListerButtons,
	&stub_Config_Menu,
	&stub_Config_Menus,
	&stub_EditFiletype,
	&stub_Config_EditFunction,
	&stub_ShowPaletteBox,
	&stub_FunctionExportASCII,
	(CONST_APTR)-1
};
