NAME := format.module

COMMON_OBJS := 	init/libinit.o format.o format_data.o format_strings.o

OS4_OBJS    :=	init/aos4_ppc_libstub.o \
				init/aos4_68k_to_ppc_vectors.o

OS3_OBJS    :=	init/68k_asm_a4_a5.o

MOS_OBJS    :=	init/mos_ppc_libstub.o
