COMMON_OBJS = 	init/libinit.o \
				ftp_ver.o  ftp_main.o ftp_lister.o ftp_lister_list.o \
				ftp_lister_xfer.o ftp_lister_connect.o ftp.o \
				ftp_arexx.o ftp_util.o ftp_recursive.o \
				ftp_addressbook.o ftp_addrsupp.o ftp_addrformat.o \
				ftp_protect.o \
				ftp_module.o ftp_data.o ftp_strings.o
